name: Deploy to GH Pages

on:
  push:
    branches: [ main ]
    paths:
    - 'dist/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        cp CNAME dist/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
